### ISSUE TITLE
Da error al descargarse cosas

### ISSUE THREAD

**Issue by JJ** [JJ/github-city-rankings#24]
```
/home/jmerelo/Code/top-github/github-city-rankings/lib/utils-node.js:91
            var sha = commits[0]['sha'];
                                ^
TypeError: Cannot read property 'sha' of undefined
  at /home/jmerelo/Code/top-github/github-city-rankings/lib/utils-node.js:91:33
  at Request.callback (/home/jmerelo/Code/top-github/github-city-rankings/node_modules/superagent/lib/node/index.js:603:30)
```
Me da la impresión de que no puede descargarse el fichero, pero no sabría decirte... Voy a tener que revertir a la versión anterior mientras tanto.

**Comment by JJ** [comment]
Me parece que el problema va a ser que no usas el API autentificado y por tanto excede el límite.

**Comment by JJ** [comment]
Vale, ya lo pillo. @iblancasa estás usando el valor que se le pasa para hacer la búsqueda, pero no siempre coincide con el nombre de la ciudad. De hecho, casi nunca.
